jQuery(function($){var form=$('#contactForm')
var formMessages=$('#contact_message')
$(form).submit(function(event){event.preventDefault()
var formData=$(form).serialize()
$.ajax({type:'POST',url:$(form).attr('action'),data:formData}).done(function(response){$(formMessages).text(response)
$('#contact_message').fadeIn(1000)
$('#name').val('')
$('#email').val('')
$('#telefono').val('')
$('#hade').val('')
$('#msg').val('')}).fail(function(data){$(formMessages).show()
if(data.responseText!==''){$(formMessages).innerText(data.responseText)}else{$(formMessages).text('Oops! An error occured and your message could not be sent.')}})})})